# Basic
title: 雅奇
subtitle: for js art
welcome_message: <a href="https://yuccie.github.io/jsArt/" target="_blank">wecome to my blog</a>
description: go ahead man.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_btns:
    - {title: Blog, description: Visit blog, url: '/#blog'}
    - {title: async, description: es6 async, url: '/#blog'}

# Navigation buttons in the front page.
nav:
    - {title: github, description: My github, url: 'https://yuccie.github.io/jsArt/'}


# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: yuccie
    github: yuccie
    twitter: yuccie
    gplus: yuccie
    mail: yuccie1617@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
